"""Add missing columns

Revision ID: 0ad18bd2b7b1
Revises: 02228d3bbcee
Create Date: 2026-08-04 02:05:28.599464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad18bd2b7b1'
down_revision: Union[str, Sequence[str], None] = '02228d3bbcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hackathon', sa.Column('results_published', sa.Boolean(), nullable=False))
    op.add_column('hackathon', sa.Column('announce_ps_advance', sa.Boolean(), nullable=False))
    op.add_column('judge_assignment', sa.Column('hackathon_id', sa.String(length=36), nullable=False))
    op.add_column('judge_assignment', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('judge_assignment', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('judge_assignment', 'submission_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(op.f('unique_judge_submission_assignment'), 'judge_assignment', type_='unique')
    op.create_unique_constraint('unique_judge_hackathon_submission_assignment', 'judge_assignment', ['hackathon_id', 'judge_id', 'submission_id'])
    op.create_foreign_key(None, 'judge_assignment', 'hackathon', ['hackathon_id'], ['id'], ondelete='CASCADE')
    op.alter_column('registration', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('registration', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('team_invitation', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('team_invitation', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('user', sa.Column('semester', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('auto_accept_invites', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auto_accept_invites')
    op.drop_column('user', 'semester')
    op.alter_column('team_invitation', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('team_invitation', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('registration', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('registration', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(None, 'judge_assignment', type_='foreignkey')
    op.drop_constraint('unique_judge_hackathon_submission_assignment', 'judge_assignment', type_='unique')
    op.create_unique_constraint(op.f('unique_judge_submission_assignment'), 'judge_assignment', ['submission_id', 'judge_id'])
    op.alter_column('judge_assignment', 'submission_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('judge_assignment', 'updated_at')
    op.drop_column('judge_assignment', 'created_at')
    op.drop_column('judge_assignment', 'hackathon_id')
    op.drop_column('hackathon', 'announce_ps_advance')
    op.drop_column('hackathon', 'results_published')
    # ### end Alembic commands ###
