"""add_file_url_status_notes_to_submission

Revision ID: 3af374299e1d
Revises: 5cd403d294a7
Create Date: 2026-07-26 21:17:21.679126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af374299e1d'
down_revision: Union[str, Sequence[str], None] = '5cd403d294a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('additional_notes', sa.Text(), nullable=True))
    op.add_column('submission', sa.Column('file_url', sa.String(length=500), nullable=True))
    op.add_column('submission', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('submission', sa.Column('status', sa.String(length=50), nullable=False, server_default='submitted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'status')
    op.drop_column('submission', 'file_name')
    op.drop_column('submission', 'file_url')
    op.drop_column('submission', 'additional_notes')
    # ### end Alembic commands ###
